# -*- coding: utf-8 -*-
"""Zotbins_Duplicate_Removing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcPVZ2NfPt_oFWQQ1o1gZiudXflq5kxe
"""

import pandas as pd
import sys

if len(sys.argv) < 3:
    print("Not enough arguments")
    print("Usage: find_duplicates.py [ORIGINAL_CSV] [OUTPUT_CSV]\n")
    print("ORIGINAL_CSV: Path to CSV original CSV")
    print("OUTPUT_CSV: Path to CSV to be created with rows of all duplicates")
    sys.exit()


barcodes = pd.read_csv(sys.argv[1])

duplicate_barcodes = barcodes.groupby('Barcode').filter(lambda x: len(x) > 1)

# Path used to write the csv file to
PATH = sys.argv[2]

duplicate_barcodes.to_csv(PATH, index=True, header=True)

